import mongoose from 'mongoose'

const lineItemSchema = new mongoose.Schema(
  {
    productId: { type: String, required: true },
    productName: { type: String, required: true },
    unitType: { type: String, default: 'Piece' },
    qtyPerUnit: { type: Number, default: 1, min: 1 },
    qty: { type: Number, default: 0, min: 0 },
    packedQty: { type: Number, default: 0, min: 0 },
    packedStockDeducted: { type: Number, default: 0, min: 0 },
    pieces: { type: Number, default: 0, min: 0 },
    barcode: { type: String, default: '' },
    baseCategory: { type: String, trim: true, default: '' },
    subCategory: { type: String, trim: true, default: '' },
    itemScanTime: { type: Date },
    unitPrice: { type: Number, default: 0, min: 0 },
    srp: { type: Number, default: 0, min: 0 },
    lineTotal: { type: Number, default: 0, min: 0 },
    discountPercent: { type: Number, default: 0, min: 0 },
    discountAmount: { type: Number, default: 0, min: 0 },
    netPrice: { type: Number, default: 0, min: 0 },
    isExchange: { type: Boolean, default: false },
    isTaxable: { type: Boolean, default: true },
    isFreeItem: { type: Boolean, default: false },
    manualEntry: { type: Boolean, default: false },
    isAddedLater: { type: Boolean, default: false },
  },
  { _id: false },
)

const orderLogSchema = new mongoose.Schema(
  {
    action: { type: String, required: true },
    byUserId: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    byUserName: { type: String, default: '' },
    at: { type: Date, default: Date.now },
  },
  { _id: false },
)

const salesOrderSchema = new mongoose.Schema(
  {
    orderNumber: { type: String, unique: true, sparse: true },
    customer: { type: mongoose.Schema.Types.ObjectId, ref: 'Customer', required: true, index: true },
    salesPerson: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, index: true },
    status: {
      type: String,
      enum: [
        'new',
        'processed',
        'add-on',
        'packed',
        'add-on-packed',
        'ready-to-ship',
        'shipped',
        'delivered',
        'undelivered',
        'close',
        'cancelled',
      ],
      default: 'new',
    },
    assignedPacker: { type: mongoose.Schema.Types.ObjectId, ref: 'User', index: true },
    packerAssignMinutes: { type: Number, default: 30, min: 1 },
    noOfPackedBoxes: { type: Number, default: 1, min: 1 },
    assignedPicker: { type: mongoose.Schema.Types.ObjectId, ref: 'User', index: true },
    assignedDriver: { type: mongoose.Schema.Types.ObjectId, ref: 'User', index: true },
    packedAt: { type: Date },
    shippedAt: { type: Date },
    deliveredAt: { type: Date },
    cancelledAt: { type: Date },
    cancelledRemark: { type: String, trim: true, default: '' },
    closedAt: { type: Date },
    logs: { type: [orderLogSchema], default: [] },
    warehouseTodo: { type: String, trim: true, default: '' },
    orderDate: { type: Date, default: Date.now },
    deliveryDate: { type: Date },
    terms: { type: String, trim: true, default: '' },
    shippingType: { type: String, trim: true, default: 'Ground Shipping' },
    billingAddress: { type: String, trim: true, default: '' },
    shippingAddress: { type: String, trim: true, default: '' },
    lineItems: [lineItemSchema],
    notes: { type: String, trim: true, default: '', maxlength: 2000 },
    salesPersonRemark: { type: String, trim: true, default: '', maxlength: 500 },
    driverRemark: { type: String, trim: true, default: '', maxlength: 500 },
    subtotal: { type: Number, default: 0 },
    overallDiscountPercent: { type: Number, default: 0, min: 0 },
    overallDiscountAmount: { type: Number, default: 0, min: 0 },
    shippingCharges: { type: Number, default: 0, min: 0 },
    taxType: { type: String, trim: true, default: '' },
    taxPercent: { type: Number, default: 0, min: 0 },
    totalTax: { type: Number, default: 0, min: 0 },
    paymentStatus: { type: String, trim: true, default: 'not_paid' },
    accountsNote: { type: String, trim: true, default: '' },
    mlQuantity: { type: Number, default: 0, min: 0 },
    mlTax: { type: Number, default: 0, min: 0 },
    weightQuantity: { type: Number, default: 0, min: 0 },
    weightTax: { type: Number, default: 0, min: 0 },
    vapeTax: { type: Number, default: 0, min: 0 },
    adjustment: { type: Number, default: 0 },
    orderTotal: { type: Number, default: 0 },
  },
  { timestamps: true },
)

export default mongoose.model('SalesOrder', salesOrderSchema)
